name: diffusion_exp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - pip=24.0
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==2.0.1+cu117
    - accelerate==0.27.2
    - diffusers==0.26.3
    - transformers==4.38.1
    - matplotlib==3.8.3
    - ipywidgets==8.1.2
    - ipykernel==6.29.2
    